# Generated by Django 3.1 on 2021-02-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_topic_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='view',
            new_name='views',
        ),
    ]
